#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Jun 16 22:22:57 2012

import wx

# begin wxGlade: extracode
# end wxGlade



class RaceTimerFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RaceTimerFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.quit_btn = wx.Button(self, -1, "Quit")
        self.reset_btn = wx.Button(self, -1, "Reset")
        self.label_1 = wx.StaticText(self, -1, "Lap")
        self.p1_laps = wx.StaticText(self, -1, "0")
        self.label_2 = wx.StaticText(self, -1, "Average")
        self.p1_avg_time = wx.StaticText(self, -1, "2.34s")
        self.label_3 = wx.StaticText(self, -1, "Best")
        self.p1_best_time = wx.StaticText(self, -1, "1.00s")
        self.p1_lap_list = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.label_1_copy = wx.StaticText(self, -1, "Lap")
        self.p2_laps = wx.StaticText(self, -1, "0")
        self.label_2_copy = wx.StaticText(self, -1, "Average")
        self.p2_avg_time = wx.StaticText(self, -1, "2.34s")
        self.label_3_copy = wx.StaticText(self, -1, "Best")
        self.p2_best_time = wx.StaticText(self, -1, "1.00s")
        self.p2_lap_list = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_quit_btn_clicked, self.quit_btn)
        self.Bind(wx.EVT_BUTTON, self.on_reset_btn_clicked, self.reset_btn)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RaceTimerFrame.__set_properties
        self.SetTitle("Race Timer")
        self.SetSize((692, 506))
        self.label_1.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.p1_laps.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_2.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.p1_avg_time.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_3.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.p1_best_time.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_1_copy.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.p2_laps.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_2_copy.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.p2_avg_time.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_3_copy.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.p2_best_time.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RaceTimerFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1_copy = wx.FlexGridSizer(3, 2, 0, 20)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 2, 0, 20)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(self.quit_btn, 0, 0, 0)
        sizer_5.Add(self.reset_btn, 0, 0, 0)
        sizer_1.Add(sizer_5, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_1, 0, 0, 0)
        grid_sizer_1.Add(self.p1_laps, 0, 0, 0)
        grid_sizer_1.Add(self.label_2, 0, 0, 0)
        grid_sizer_1.Add(self.p1_avg_time, 0, 0, 0)
        grid_sizer_1.Add(self.label_3, 0, 0, 0)
        grid_sizer_1.Add(self.p1_best_time, 0, 0, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_3.Add(grid_sizer_1, 0, wx.EXPAND, 0)
        sizer_3.Add(self.p1_lap_list, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        grid_sizer_1_copy.Add(self.label_1_copy, 0, 0, 0)
        grid_sizer_1_copy.Add(self.p2_laps, 0, 0, 0)
        grid_sizer_1_copy.Add(self.label_2_copy, 0, 0, 0)
        grid_sizer_1_copy.Add(self.p2_avg_time, 0, 0, 0)
        grid_sizer_1_copy.Add(self.label_3_copy, 0, 0, 0)
        grid_sizer_1_copy.Add(self.p2_best_time, 0, 0, 0)
        grid_sizer_1_copy.AddGrowableCol(1)
        sizer_4.Add(grid_sizer_1_copy, 0, wx.EXPAND, 0)
        sizer_4.Add(self.p2_lap_list, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def on_quit_btn_clicked(self, event): # wxGlade: RaceTimerFrame.<event_handler>
        print "Event handler `on_quit_btn_clicked' not implemented!"
        event.Skip()

    def on_reset_btn_clicked(self, event): # wxGlade: RaceTimerFrame.<event_handler>
        print "Event handler `on_reset_btn_clicked' not implemented!"
        event.Skip()

# end of class RaceTimerFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    raceTimerFrame = RaceTimerFrame(None, -1, "")
    app.SetTopWindow(raceTimerFrame)
    raceTimerFrame.Show()
    app.MainLoop()
